ACCESS-NRI/access-esm1.5-configs

config.yaml
manifests/exe.yaml
manifests/input.yaml

Closes #16
The `payu` test run reproduces the relevant outputs bitwise.

Use the latest spack executables in the pre-industrial config

---

atmosphere/cable.nml
config.yaml
manifests/input.yaml
manifests/restart.yaml

This pull request updates the input paths for the historical configuration with the restructured filepaths, relating to #37.
The md5 hash for `cableCMIP6_LC_1850-2015.nc` has changed due to the changes in  #22.
The md5 hashes for the following input files:
- `BC_hi_1849_2015_ESM1.anc`
- `Bio_1849_2015_ESM1.anc`
- `OCFF_1849_2015_ESM1.anc`
- `ozone_1849_2015_ESM1.anc`
- `scycl_1849_2015_ESM1_v4.anc`
have changed as the `vk83` version of these files are sourced from `/g/data/access/payu/access-esm/input/historical.corrected/` rather than `/g/data/access/payu/access-esm/input/historical/`. These then match the ancillaries from the CMIP6 script runs located in `/g/data/p66/txz599/data/ancil/CMIP6/`. See [here](https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/22#issuecomment-219279209 …

37 update input paths historical

---

atmosphere/cable.nml
config.yaml
manifests/input.yaml
manifests/restart.yaml

This pull request updates the pre-industrial configuration with the new input paths using the restructured directory.
Note that the md5 hash for `pftlookup_csiro_v16_17tiles_wtlnds.csv` changed as there are slight differences between the `~access/payu` and the `vk83` versions of the file which [but the differences don't appear to be used by the model](https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/2#issuecomment-2190327672).

37 update input paths pre-industrial

---

config/ci.json

In this PR:
* Update the version of `model-config-tests` used to `0.0.4` - bugfixes to valid testing values
See referenced https://github.com/ACCESS-NRI/model-config-tests/pull/43

Updated `model-config-tests` to `0.0.4`

---

config/ci.json

In this PR:
* Update the version of `model-config-tests` used to `0.0.5` - in which there are further fixes to QA tests for metadata.yaml. 
References https://github.com/ACCESS-NRI/model-config-tests/pull/45

Update `model-config-tests` version to `0.0.5`

---

config/ci.json

See changes here: https://github.com/ACCESS-NRI/model-config-tests/pull/46
In this PR:
* Update `model-config-tests` used to new `0.0.6`

Update `model-config-tests` to `0.0.6`

---

config/ci.json

Update the version of `model-config-tests` to `0.0.7` -  see https://github.com/ACCESS-NRI/model-config-tests/pull/47

Update model-config-tests to `0.0.7`

---

.github/workflows/generate-initial-checksums.yml
README-DEV.md
config/ci.json

In this PR:
* Updated `config/ci.json` schema to `2-0-0` - see https://github.com/ACCESS-NRI/schema/pull/35 NOTE: the validation CI will fail until this is merged
* Added global default `payu-version` `1.1.4`
Updated repo settings:
* Added `vars.MODULE_LOCATION` and `vars.PRERELEASE_MODULE_LOCATION`. See https://github.com/ACCESS-NRI/access-esm1.5-configs/settings/environments
* Update `vars.CONFIG_CI_SCHEMA_VERSION` to `2-0-0`. See https://github.com/ACCESS-NRI/access-esm1.5-configs/settings/variables/actions
References ACCESS-NRI/model-config-tests#37

`config/ci.json`: Added global default `payu-version` `1.1.4`

---

scripts/update_landuse_driver.sh

This PR will close #56. It adds a check to see whether an end of year restart exists before running the `update_landuse.py` script, which will allow reproducibility tests to be done with shorter runs.
If no end of year restart exists, I've added in a warning message – though any suggestions on what the message should say are welcome.
Let me know if you have any suggestions/improvements!
Note that this change doesn't resolve issues related to non-standard run lengths (such as 8 months or 2 years), which will be looked at in a separate issue.

Don't run land use change on simulations shorter than a year.

---

config/ci.json

We need an updated version of `payu` to support ACCESS-ESM1.5.
Once this version has been deployed when https://github.com/ACCESS-NRI/payu-condaenv/pull/41#pullrequestreview-2256165092 is merged, this PR also needs to be merged.

Update payu version in CI

---

ocean/input.nml

Fixes #63, uses the same axes settings as the preindustrial configuration.

Fix ocean axes settings

---

config.yaml
scripts/NetCDF-conversion/UM_conversion_job.sh

This pull request adds the um2nc based netcdf conversion as a postscript to the preindustrial configuration. Fields file deletion is switched on by default.

Add netcdf conversion to preindustrial configuration

---

config.yaml
scripts/update_landuse.py
scripts/update_landuse_driver.sh

This pull request adds a workaround for #57, it replaces the python interpreter in the `update_landuse.py` script to `#!/usr/bin/env python3`, and loads the `payu` environment in the driving `update_landuse_driver.sh` script, to ensure the payu python interpreter is used. 
The `hh5` storage directive is also removed from the `config.yaml` as it is no longer needed.

57 landuse python interpreter

---

scripts/update_landuse.py
scripts/update_landuse_driver.sh

Fixes #67 
Removes `module use` that was throwing an error and hard-codes a python interpreter path in the update landuse python script.
I have tested this doesn't throw an error. I have not tested that it runs correctly after a 1 year run.

Hard code python interpreter path in landuse change script

---

ocean/diagnostic_profiles/diag_table_detailed
ocean/diagnostic_profiles/diag_table_standard
ocean/diagnostic_profiles/source_yaml_files/diag_table_detailed_source.yaml
ocean/diagnostic_profiles/source_yaml_files/diag_table_standard_source.yaml

A few updates to the MOM5 diagnostic tables:
Closes #72, closes #74
(Once this is merged I'll cherry-pick to `dev-historical+concentrations`)

Update MOM5 diagnostic tables: `historical+concentrations`

---

README.md
config.yaml
manifests/exe.yaml
manifests/input.yaml
manifests/restart.yaml

Updates to `access-esm1p5` 2024.05.1 which allows us to remove usused BGC inputs. Also fixes a small typo in the README.
Will cherry-pick to `historical+concentrations` once merged.
Closes #78

Update to `access-esm1p5` 2024.05.1: `preindustrial+concentrations`

---

config.yaml

This pull request increases the `jobfs` requested for the historical configuration to `1500MB` from the default `800MB`, with the goal of avoiding `jobfs exceeded` errors. 
Closes historical half of #83.

Historical - Increase jobfs to 1500MB

---

config.yaml

This pull request increases the `jobfs` requested for the historical configuration to `1500MB` from the default `800MB`, with the goal of avoiding `jobfs exceeded` errors. 
Closes preindustrial half of #83.

Preindustrial - increase jobfs to 1500MB

---

.github/workflows/ci.yml

In this PR:
- Added `on.create` trigger from https://github.com/ACCESS-NRI/model-configs-template/commit/a1988f076af334d23da3e903b490e6a24f0421bf (from ACCESS-NRI/model-configs-template#3)
NOTE: We only have to add this CI to `main` (and not other `dev-*`/`release-*` branches) because only future configurations (which are based on `ci.yml` from `main`) will require this feature. 
References ACCESS-NRI/model-config-tests#58

Added `on.create` Trigger

---

config.yaml
manifests/input.yaml
ocean/input.nml

Closes the preindustrial half of #95. 
This PR sets MOM to read the `basin_mask.nc` input file which allows for basin specific tracer diagnostics (e.g. ` temp_merid_flux_over_atlantic`) to be saved.

Preindustrial: add basin mask for basin specific diagnostics

---

config.yaml
manifests/input.yaml
ocean/input.nml

Closes the historical half of https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/95.
This PR sets MOM to read the basin_mask.nc input file which allows for basin specific tracer diagnostics (e.g.  temp_merid_flux_over_atlantic) to be saved.

Historical: add basin mask for basin specific diagnostics 

---

config.yaml
manifests/exe.yaml

This PR updates the model version to 2024.12.0 in order to include the UM orbital parameter code changes. It closes the historical half of https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/114.

Historical: update model version to 2024.12.0

---

config.yaml
manifests/exe.yaml

This PR updates the model version to `2024.12.0` in order to include the UM orbital parameter code changes. It closes the preindustrial half of #114.

Preindustrial: update to model version 2024.12.0

---

config.yaml

Closes the historical half of #111. This PR adds `payu_minimum_version: 1.1.6` to the config.yaml file to make sure the cice restart date bugfixes from https://github.com/payu-org/payu/pull/539 are included.

Add minimum payu 1.1.6 - historical

---

config.yaml

Closes the preindustrial half of #111. This PR adds `payu_minimum_version: 1.1.6` to the config.yaml file to make sure the cice restart date bugfixes from https://github.com/payu-org/payu/pull/539 are included.

Add minimum payu 1.1.6 - preindustrial

---

manifests/input.yaml

PR #107 Updated the inputs to use new STASH files – unfortunately I forgot to add the corresponding update to the input manifetsts. This PR updates the manifests with the new files.

Update manifests for new stashmaster files - Pre-industrial

---

manifests/input.yaml

PR #108 Updated the inputs to use new STASH files for the historical configuration – unfortunately I forgot to add the corresponding update to the input manifetsts. This PR updates the manifests with the new files.

Update input manifest for modified stash files - Historical

---

config/ci.json

In this PR:
- We add scheduled checks for the above config tags, so we test whether the continue to be reproducible with themselves month-to-month.

Add scheduled checks for release-historical+concentrations-1.2 and release-preindustrial+concentrations-1.2

---

.github/workflows/generate-initial-checksums.yml

References ACCESS-NRI/access-esm1.6-configs#73
Similar to the linked issue, a later workflow requires `permissions.checks: write` but we don't give that in the caller. Now we do!
* Give `repro-ci` `permissions.checks: write`

Add checks: write permission

---

config.yaml
manifests/exe.yaml

This PR updates to access-esm1.5 2024.12.1, which includes:
- Updates MOM5 to [access-esm1.5-2025.03.002](https://github.com/ACCESS-NRI/MOM5/releases/tag/access-esm1.5-2025.03.002), which includes
- WOMBAT fix to prevent negative Schmidt numbers in warm temperatures (https://github.com/ACCESS-NRI/MOM5/pull/36)
- Updates for oneapi (https://github.com/ACCESS-NRI/MOM5/pull/32)
- Updates `spack-packages` to [2025.03.006](https://github.com/ACCESS-NRI/spack-packages/releases/tag/2025.03.006)
- Updates CICE4 to [access-esm1.5-2025.04.001](https://github.com/ACCESS-NRI/cice4/releases/tag/access-esm1.5-2025.04.001) which includes
-  CICE error reporting changes so that error messages are written to stderr, and non-zero exit codes are used (https://github.com/ACCESS-NRI/cice4/pull/14)
Contributes …

Update to access-esm1.5 2024.12.1: `dev-preindustrial+concentrations`

---

config.yaml
manifests/exe.yaml

This PR updates to access-esm1.5 2024.12.1, which includes:
- Updates MOM5 to [access-esm1.5-2025.03.002](https://github.com/ACCESS-NRI/MOM5/releases/tag/access-esm1.5-2025.03.002), which includes
- WOMBAT fix to prevent negative Schmidt numbers in warm temperatures (https://github.com/ACCESS-NRI/MOM5/pull/36)
- Updates for oneapi (https://github.com/ACCESS-NRI/MOM5/pull/32)
- Updates `spack-packages` to [2025.03.006](https://github.com/ACCESS-NRI/spack-packages/releases/tag/2025.03.006)
- Updates CICE4 to [access-esm1.5-2025.04.001](https://github.com/ACCESS-NRI/cice4/releases/tag/access-esm1.5-2025.04.001) which includes
-  CICE error reporting changes so that error messages are written to stderr, and non-zero exit codes are used (https://github.com/ACCESS-NRI/cice4/pull/14)
Contributes …

Update to access-esm1.5 2024.12.1: `dev-historical+concentrations`
